name: Deploy Website

on:
  push:
    branches:
      - main # Ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- OPCIONAL: Se precisar rodar Build (React, Vue, Node, etc) ---
      # - name: Install Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: npm install
      # - run: npm run build
      # -------------------------------------------------------------

      - name: Deploy to Server via Rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/" # Pasta com os arquivos gerados (ex: dist, build, ou . para tudo)
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "/var/www/madamebaunilha.com.br/teste" # Pasta de destino no servidor
